A DESKTOP NOTIFIER IS A SAMPLE APPLICATION WHICH PRODUCES A NOTIFICIATION MESSAGE IN THE FORM OF A POP UP MESSAGE ON DESKTOP.
------------
import win10toast
from win10toast import ToastNotifier
#CREATING OBJECT TO TOAST NOTIFIER CLASS
n=ToastNotifier()
n.show_toast("ROCKY","YOU GOT SOME NOTIFICATION",duration=10)